const String HIVE_BOX_NAME = 'HIVE_BOX_NAME';

//take away billing data
const String HIVE_TAKE_AWAY_BILL = 'HIVE_TAKE_AWAY_BILL';
//home delevery billing data
const String HIVE_HOME_DELEVERY_BILL = 'HIVE_HOME_DELEVERY_BILL';
//online booking billing data
const String HIVE_ONLINE_BOOKING_BILL = 'HIVE_ONLINE_BOOKING_BILL';
//dining billing data
const String HIVE_DINING_BILL = 'HIVE_DINING_BILL';

const  String HIVE_DATABASE_BILLING_ITEMS = "HOLD_BILLING_ITEMS";

const  String HIVE_DATABASE_DELIVERY_ADDRESS_ITEMS = "DELIVERY_ITEMS";

//application mode number 1 is cashir , 2 is waiter , 3 is kitchhen
const String HIVE_APP_MODE_NUMBER = 'HIVE_APP_MODE_NUMBER';

const String HIVE_SHOP_DETAILS = 'HIVE_SHOP_DETAILS';

const String HIVE_NOTICE_UPDATE_DETAILS = 'HIVE_NOTICE_UPDATE_DETAILS';

const String HIVE_SHOW_ADDRESS_IN_BILL = 'HIVE_SHOW_ADDRESS_IN_BILL';

const String HIVE_KOT_RING_SOUND = 'HIVE_KOT_RING_SOUND';

const String HIVE_KOT_REMEMBER_RING_SOUND = 'HIVE_KOT_REMEMBER_RING_SOUND';

const String ALLOW_CREDIT_BOOK_TO_WAITER = 'ALLOW_CREDIT_BOOK_TO_WAITER';

const String ALLOW_PURCHASE_BOOK_TO_WAITER = 'ALLOW_CREDIT_BOOK_TO_WAITER';

const String INTERVEL_COUNT_TO_CALL_EXPAIRY = 'INTERVEL_COUNT_TO_CALL_EXPAIRY';

const String SET_SHOW_PRICE_IN_HIVE = 'SET_SHOW_PRICE_IN_HIVE';
const String SET_SHOW_SPECIAL_IN_HIVE = 'SET_SHOW_SPECIAL_IN_HIVE';
const String SET_AVAILABLE_ONLY_IN_HIVE = 'SET_AVAILABLE_ONLY_IN_HIVE';

const  String HIVE_DATABASE_FREQUENT_ITEMS = "HIVE_DATABASE_FREQUENT_ITEMS";

const String SHOW_ERROR = 'SHOW_ERROR';